export const surpriseMePrompts = [
  "un fauteuil en forme d'avocat",
  "une peinture à l'huile surréaliste de Salvador Dalí représentant un chat jouant aux dames",
  "des ours en peluche faisant leurs courses au Japon, ukiyo-e",
  "une peinture à l'huile de Matisse représentant un robot humanoïde jouant aux échecs",
  "un panda scientifique fou mélangeant des produits chimiques étincelants, art numérique",
  "une photographie macro 35mm de deux souris à Hawaii, portant chacune un petit maillot de bain et une petite planche de surf, art numérique",
  "rendu 3D d'un joli poisson tropical dans un aquarium sur fond bleu foncé, art numérique",
  "un astronaute se prélassant dans une station balnéaire tropicale dans l'espace, vaporwave",
  "un portrait à l'huile d'un capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre",
  "une fenêtre en vitrail représentant un hamburger et des frites",
  "un dessin à la mine de plomb et à l'aquarelle d'une ville lumineuse du futur avec des voitures volantes",
  "un espace de détente ensoleillé avec une piscine d'eau claire et une autre piscine d'eau rose pastel translucide, à côté d'une grande fenêtre, art numérique",
  "un shiba inu pratiquant la divination en lisant votre destin dans un énorme hamburger, art numérique",
  "une loutre de mer avec une boucle d'oreille en perle de Johannes Vermeer",
  "un dessin à la craie à l'huile d'un chat agacé dans un vaisseau spatial",
  "un tableau représentant un renard dans le style de la Nuit étoilée",
  "un bol de soupe qui ressemble à un monstre, tricoté en laine",
  "un robot en peluche assis contre un mur jaune",
  "un coucher de soleil de style synthwave au-dessus de l'eau réfléchissante de la mer, art numérique",
  "deux tours futuristes avec une passerelle couverte de feuillage luxuriant, art numérique",
  "un ballon à air chaud coloré en arc-en-ciel volant au-dessus d'un lac réfléchissant, rendu 3D",
  "une couverture de bande dessinée d'un super-héros portant des écouteurs",
  "une explosion colorée de poudre sur un fond noir centré",
  "une photo d'un chien Samoyède avec la langue sortie en train d'enlacer un chat siamois blanc",
  "une photo d'un monstre en fourrure blanche debout dans une pièce violette",
  "une photo de la sculpture de David de Michel-Ange portant des écouteurs de DJ",
  "un samouraï chevauchant un cheval sur Mars, lomographie",
  "une Cadillac moderne et élégante roulant le long de l'autoroute Gardiner avec le centre-ville de Toronto en arrière-plan, avec une lueur de lentille, photographie 50mm",
  "Deux tours futuristes reliées par un pont couvert de feuillage luxuriant, art numérique",
  "Une montgolfière multicolore en 3D volant au-dessus d'un lac réfléchissant les couleurs de l'arc-en-ciel",
  "La couverture d'une bande dessinée d'un super-héros portant des écouteurs",
  "Une explosion de poudre colorée centrée sur un fond noir",
  "Une photo d'un chien Samoyède avec la langue sortie en train de câliner un chat Siamois blanc",
  "Une photo d'un monstre en fourrure blanche debout dans une pièce violette",
  "Une photo de la sculpture de David de Michel-Ange portant des écouteurs en train de mixer",
  "Un samouraï chevauchant un cheval sur Mars, lomographie.",
  "Une Cadillac moderne et élégante circulant sur l'autoroute Gardiner avec le centre-ville de Toronto en arrière-plan, avec un effet de flare, photographie 50mm",
  "Une photographie réaliste d'une jeune femme aux yeux bleus et aux cheveux blonds",
  "Un homme se tenant devant une porte des étoiles menant à une autre dimension",
  "Bob l'éponge dans le Projet Blair Witch",
  "Un vélociraptor travaillant dans un stand de hot-dogs, lomographie",
  "Un homme marchant dans les rues animées de Kowloon la nuit, éclairées par de nombreux panneaux lumineux en néon, objectif 50mm",
  "Un barbecue vivant, dans le style d'un film d'animation Pixar",
  "Un club de danse de cyborgs futuriste, lumières néon",
  "La Star Wars 1990 Japanese Anime, longtemps perdue",
  "Un hamburger en forme de Rubik's cube, photographie culinaire professionnelle",
  "Un hérisson Synthwave, Blade Runner Cyberpunk",
  "Un astronaute rencontrant une forme de vie extraterrestre sur une planète lointaine, photographie",
  "Un dinosaure explorant Cape Town, photographie",
  "Un homme tombant amoureux de son ordinateur, art numérique",
  "Une photographie d'un cyborg explorant Tokyo la nuit, lomographie",
  "Dracula marchant dans les rues de New York dans les années 1920, photographie en noir et blanc",
  "Avion Synthwave",
  "Un homme se promenant dans les rues pluvieuses de Tokyo, éclairées par de brillants panneaux lumineux en néon, objectif 50mm",
  "Une navette spatiale volant au-dessus de Cape Town, art numérique",
];
